language: node_js
env:
  global:
    secure: xvAnloVf5TagqDTqhhcuyCUII3r3smnNHkUgeLaLmTZ2aSUQb1//sn+altBN3QVEbL4qozA2qKOJSCEYXeLtuqnXgrHIkBR3aD1UFou1yvSjaG+57i1UhfI9pp2qbRTjZ8w3EVigcMqx/iEaT1Pg5PaKzggyl2OW9rfNWB/Sv9c97N4mbFAY4V6kqjWOS+YL0F1vXtfZFwaF+HGZoE8e5RFOpCdyTcr0p0heJrVFd6yHaKxnkSvOylPoGDHX5Qv64l9Y+kMsoZ5j8oWF0PouwlYRk90uPHG33gD5Ef7hI9T3XAWslM7uRQLDBo80fpdZPO2a97/fevpy259qafYDNMiwm3TuYIslQzdZu+1U2Df+6ypKwwfUhrADfNjAF4SoQAaE2r4hZKd6r2YP+0sVHCJUDKKgVaL5+ktlBJNUCxo3nmMf2r30D11Jr91Ln3TXcWUyg/YQie85cozjcGT/Mctu7Ey3JuRrb/viUj+Jc6jYC4zh+geCf4p1Yy72tVKcKrL1G0Iq/ds1Lc8H2zyQjjmOoAHq4DBWArtcRf8a2xdjxhyC4rNLu5JtjwCehi3SSBeCytnpkHslXhIiGqtwN8SG0s+PWBNnZdXvAFfj3b7dNYAmhherI4/g+HPsO+FbvzI751Q4mdFDJBBrPLZ3I2b/z0zMwN3AUnfGhzu7fT0=
node_js:
  - stable
cache:
  directories:
    - node_modules
notifications:
  email: false
jobs:
  include:
    - stage: Tests
      name: Unit Tests
      before_script:
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - ./cc-test-reporter before-build
      script: yarn test --coverage
      after_script:
        - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
    - stage: Build
      name: Production Build
      script: yarn build
    - stage: Production Deployment
      name: Deployment to Heroku
      script: skip
      deploy: &heroku
        provider: heroku
        app: snt-frontend
        api_key:
          secure: kvaF1MEa8vClU7wgTeq7A+Bfz9TVR7vzVYiMlMBdn0oZ/kxwIjKsKAnHpq3fW0qhnfpNrjS7Y8a4qKhsmG7YWVSE2TbI+l8WusxEFNYY8vnZFPVioRNa8iLmqlcmsCwBml9TrcPDBpX/8qAkGlPJ7wOwXGYcpjbjtmb0DPqg8iGBuSbJ4n0diuDE5lO8VA1s+augwDvq97IET5TfkQO1wvnF92Mo7XyENm1X9luSmaOvURmWXfnqLpXQu4CwWfyou4pycApMJ080j3Vt9B1vR8X4RIXnQ5BKqmvOP8WJLi8G8Fx8UrBECjZLaOLhlEXHIEBzAFr4WUiif3f16HnxgvbX9G+BDq9/gWHrNioliDKEo90K3yx1MIxdvHiqQ3x6ehXnvOmAAJf2Jr6dVghkPIcO39pLUAQApqZR6RSskTmg5d7LRk2b8TWwrYKq4vHL+JwGa3o30iHFcMkt7LE3kn1QonheN5pSYl1+34+7OYQKKU94adK5Ho7s2Il+mzG3Lq9RehgP7pWYHJCmibe0U4Ul2WIWyGoQJw3l8VVKtD2HqRTsfNRJHqnnRkJL5VMGvcHu8Uy0kUjvSyDsiS+jbChnUq2Nlane6peFE2BG6tXrsBxhmQ0z0DLMQx/8Y69BIPFVYyrxA9mdzO8NG0xmSmAPwJWk9oGZXC6KlLNNKls=
        on:
          repo: msoufiane/master
