language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules

jobs:
  include:
    - stage: Tests
      name: "Unit Tests"
      script: yarn test --coverage
    - stage: Build
      name: "Production Build"
      script: yarn build
