import {
  ControlSideBarMenu,
  ControlSideBarItem,
  Version,
  CopyRight,
  Footer,
  NavbarLogo,
  NavbarMenu,
  NavbarToggle,
  ControlSideBarButton,
  ProfileContainer,
  Settings,
  Notifications,
  Messages,
  SideBarMenu,
  MenuItem,
  MenuTree,
  AppWrapper,
  HeaderWrapper,
  SideBarWrapper,
  ControlSideBarWrapper,
  ContentWrapper,
  HomePage,
  NotFoundPage
} from "./index";

it("all exports are working", () => {
  expect(ControlSideBarMenu).toBeDefined();
  expect(ControlSideBarItem).toBeDefined();
  expect(Version).toBeDefined();
  expect(CopyRight).toBeDefined();
  expect(Footer).toBeDefined();
  expect(NavbarLogo).toBeDefined();
  expect(NavbarMenu).toBeDefined();
  expect(NavbarToggle).toBeDefined();
  expect(ControlSideBarButton).toBeDefined();
  expect(ProfileContainer).toBeDefined();
  expect(Settings).toBeDefined();
  expect(Notifications).toBeDefined();
  expect(SideBarMenu).toBeDefined();
  expect(MenuTree).toBeDefined();
  expect(MenuItem).toBeDefined();
  expect(AppWrapper).toBeDefined();
  expect(HeaderWrapper).toBeDefined();
  expect(SideBarWrapper).toBeDefined();
  expect(ContentWrapper).toBeDefined();
  expect(ControlSideBarWrapper).toBeDefined();
  expect(Messages).toBeDefined();
  expect(HomePage).toBeDefined();
  expect(NotFoundPage).toBeDefined();
});
